# Generated by Django 4.2.5 on 2023-09-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(db_index=True, max_length=100, verbose_name='customer')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=100, verbose_name='make')),
                ('model', models.CharField(db_index=True, max_length=100, verbose_name='model')),
                ('year', models.IntegerField(db_index=True, verbose_name='year')),
            ],
            options={
                'verbose_name': 'car model',
                'verbose_name_plural': 'car models',
                'ordering': ['make', 'model', 'year'],
            },
        ),
        migrations.CreateModel(
            name='PartService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
            ],
            options={
                'verbose_name': 'part or service',
                'verbose_name_plural': 'parts and services',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.car', verbose_name='car')),
            ],
            options={
                'verbose_name': 'service order',
                'verbose_name_plural': 'service orders',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='autoservisas.serviceorder', verbose_name='order')),
                ('part_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='autoservisas.partservice', verbose_name='part service id')),
            ],
            options={
                'verbose_name': 'order line',
                'verbose_name_plural': 'order lines',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoservisas.carmodel', verbose_name='car model'),
        ),
    ]
