# Generated by Django 4.2.5 on 2023-10-08 13:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partservice',
            name='details',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='details'),
        ),
    ]
