# Generated by Django 4.2.5 on 2023-10-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_partservicereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='customer',
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'confirmed'), (1, 'processing'), (2, 'completed'), (3, 'cancelled')], default=0, verbose_name='status'),
        ),
    ]
